angularinv/urls.py
from django.conf.urls import include, url
from django.views.generic import TemplateView

urlpatterns = [
	    url(r'^dashboard.html$', TemplateView.as_view(template_name="angularinv/dashboard.html")),
	    url(r'^bodegas.html$', TemplateView.as_view(template_name="angularinv/inventario.html")),
	    url(r'^recetas.html$', TemplateView.as_view(template_name="angularinv/recetas.html")),
	    url(r'^requisicion.html$', TemplateView.as_view(template_name="angularinv/requisicion.html")),
	    url(r'^ventas.html$', TemplateView.as_view(template_name="angularinv/ventas.html")),
	    url(r'^form/requisicion.html$', TemplateView.as_view(template_name="angularinv/formRequisicion.html")),
	    url(r'^dirPagination.tpl.html$', TemplateView.as_view(template_name="angularinv/dirPagination.tpl.html")),
	    url(r'^singleRequisicion.html$', TemplateView.as_view(template_name="angularinv/singleRequisicion.html")),

]

inventario/urls.py
from django.conf.urls import include, url
import views

urlpatterns = [
	#forms
	url(r'almacen/form/$', views.AlmacenFormView.as_view(), name="almacen_form"),
	url(r'producto/form/$', views.ProductoFormView.as_view(), name="producto_form"),
	url(r'proveedor/form/$', views.ProveedorFormView.as_view(), name="proveedor_form"),
	url(r'presentacion/form/$', views.PresentacionFormView.as_view(), name="presentacion_form"),
	url(r'entrada/form/$', views.EntradaFormView.as_view(), name="entrada_form"),
	url(r'salida/form/$', views.SalidaFormView.as_view(), name="salida_form"),
	url(r'requisiciondecompra/form/$', views.RequisicionDeCompraFormView.as_view(), name="requisiciondecompra_form"),
	url(r'solicituddeproducto/form/$', views.SolicitudDeProductoFormView.as_view(), name="solicituddeproducto_form"),

	#lists
	url(r'producto/list/$', views.ProductoListView.as_view(), name="producto_list"),
	url(r'proveedor/list/$', views.ProveedorListView.as_view(), name="proveedor_list"),
	url(r'presentacion/list/$', views.PresentacionListView.as_view(), name="presentacion_list"),
	url(r'entrada/list/$', views.EntradaListView.as_view(), name="entrada_list"),
	url(r'salida/list/$', views.SalidaListView.as_view(), name="salida_list"),
	url(r'requisiciondecompra/list/$', views.RequisicionDeCompraListView.as_view(), name="requisiciondecompra_list"),
	url(r'solicituddeproducto/list/$', views.SolicitudDeProductoListView.as_view(), name="solicituddeproducto_list"),

	#detail
	url(r'requisiciondecompra/detail/(?P<pk>[-\w]+)/', views.RequisiscionDeCompraDetail.as_supra_view(), name="requisiciondecompradetail_list"),

	#delete
	url(r'solicituddeproducto/delete/(?P<pk>[-\w]+)/$', views.SolicitudDeProductoDeleteView.as_view(), name="solicituddeproducto_delete"),

]

restaurante/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.views.generic import TemplateView
import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^inventario/', include('inventario.urls')),
    url(r'^angularinv/', include('angularinv.urls')),
    url(r'^$', TemplateView.as_view(template_name="index.html")),

]

if settings.DEBUG:
    urlpatterns += patterns('django.views.static',
        (r'media/(?P<path>.*)', 'serve', {'document_root': settings.MEDIA_ROOT}),
)

inventario/models.py
from django.db import models
from django.contrib.auth.models import User
from cuser.fields import CurrentUserField
from django.core import validators

class Almacen(models.Model):
	usuario = CurrentUserField(add_only=True)
	nombre = models.CharField(max_length=45)
	fecha_agregado = models.DateTimeField(auto_now_add=True)
#end class

class Producto(models.Model):
	almacen = models.ForeignKey(Almacen)
	usuario = CurrentUserField(add_only=True)
	nombre = models.CharField(max_length=45)
	fecha_agregado = models.DateTimeField(auto_now_add=True)
#end class

class Proveedor(models.Model):
	usuario = CurrentUserField(add_only=True)
	nombre = models.CharField(max_length=45)
	fecha_agregado = models.DateTimeField(auto_now_add=True)
#end class

class Presentacion(models.Model):
	usuario = CurrentUserField(add_only=True)
	producto = models.ForeignKey(Producto)
	nombre = models.CharField(max_length=45)
	unidades = models.DecimalField(max_digits=6, decimal_places=2, validators=[validators.MinValueValidator(0)])
	fecha_agregado = models.DateTimeField(auto_now_add=True)
#end class

class Entrada(models.Model):
	usuario = CurrentUserField(add_only=True)
	codigo = models.CharField(max_length=45)
	producto = models.ForeignKey(Producto)
	presentacion = models.ForeignKey(Presentacion)
	cantidad = models.PositiveIntegerField()
	proveedor = models.ForeignKey(Proveedor)
	valor_unitario = models.DecimalField(max_digits=6, decimal_places=2, validators=[validators.MinValueValidator(0)])
	ubicacion = models.CharField(max_length=100)
	fecha = models.DateTimeField(auto_now_add=True)

	def importe(self):
		return self.valor_unitario*self.cantidad
	#end def
#end class

class Salida(models.Model):
	usuario = CurrentUserField(add_only=True)
	entrada = models.ForeignKey(Entrada)
	cantidad = models.DecimalField(max_digits=6, decimal_places=2, validators=[validators.MinValueValidator(0)])
	fecha = models.DateTimeField(auto_now_add=True)
#end class

class RequisicionDeCompra(models.Model):
	codigo = models.CharField(max_length=45)
	usuario = CurrentUserField(add_only=True)
	fecha = models.DateTimeField(auto_now_add=True)
#end class

class SolicitudDeProducto(models.Model):
	requisiciondecompra = models.ForeignKey(RequisicionDeCompra)
	producto = models.ForeignKey(Producto)
	presentacion = models.ForeignKey(Presentacion)
	cantidad = models.PositiveIntegerField()
#end class

inventario/forms.py
from django import forms
from django.forms.models import inlineformset_factory, modelformset_factory
import models

class AlmacenForm(forms.ModelForm):
	class Meta:
		model = models.Almacen
		exclude = ()
	#end class
#end class

class ProductoForm(forms.ModelForm):
	class Meta:
		model = models.Producto
		exclude = ()
	#end class
#end class

class ProveedorForm(forms.ModelForm):
	class Meta:
		model = models.Proveedor
		exclude = ()
	#end class
#end class

class PresentacionForm(forms.ModelForm):
	class Meta:
		model = models.Presentacion
		exclude = ()
	#end class
#end class

class EntradaForm(forms.ModelForm):
	class Meta:
		model = models.Entrada
		exclude = ()
	#end class
#end class

class SalidaForm(forms.ModelForm):
	class Meta:
		model = models.Salida
		exclude = ()
	#end class
#end class

class RequisicionDeCompraForm(forms.ModelForm):
	class Meta:
		model = models.RequisicionDeCompra
		exclude = ()
	#end class
#end class

class SolicitudDeProductoForm(forms.ModelForm):
	class Meta:
		model = models.SolicitudDeProducto
		exclude = ()
	#end class
#end class

angularinv/views.py
from django.shortcuts import render

# Create your views here.

inventario/views.py
from django.shortcuts import render
from supra import views as supra
import models
import forms
from pdf import views as pdf


"""
	FORMS

"""

class AlmacenFormView(supra.SupraFormView):
	model = models.Almacen
	form_class = forms.AlmacenForm
#end class

class ProductoFormView(supra.SupraFormView):
	model = models.Producto
	form_class = forms.ProductoForm
#end class

class ProveedorFormView(supra.SupraFormView):
	model = models.Proveedor
	form_class = forms.ProveedorForm
#end class

class PresentacionFormView(supra.SupraFormView):
	model = models.Presentacion
	form_class = forms.PresentacionForm
#end class

class EntradaFormView(supra.SupraFormView):
	model = models.Entrada
	form_class = forms.EntradaForm
#end class

class SalidaFormView(supra.SupraFormView):
	model = models.Salida
	form_class = forms.SalidaForm
#end class


class SolicitudDeProductoFormView(supra.SupraInlineFormView):
	base_model = models.RequisicionDeCompra
	inline_model = models.SolicitudDeProducto
	form_class = forms.SolicitudDeProductoForm
#end class

class RequisicionDeCompraFormView(supra.SupraFormView):
	model = models.RequisicionDeCompra
	form_class = forms.RequisicionDeCompraForm
	inlines = [SolicitudDeProductoFormView]
#end class

"""
	LISTS

"""

class AlmacenListView(supra.SupraListView):
	model = models.Almacen
#end class

class PresentacionListView(supra.SupraListView):
	model = models.Presentacion
	class Renderer:
		username = 'usuario__username'
	#end class
#end class

class ProductoListView(supra.SupraListView):
	model = models.Producto
	list_display = ['id', 'almacen', 'almacenado_en', 'username', 'nombre', 'fecha_agregado']
	class Renderer:
		almacenado_en = 'almacen__nombre'
		username = 'usuario__username'
		presentaciones = PresentacionListView
	#end class
#end class

class ProveedorListView(supra.SupraListView):
	model = models.Proveedor
	class Renderer:
		username = 'usuario__username'
	#end class
#end class

class EntradaListView(supra.SupraListView):
	model = models.Entrada
	class Renderer:
		username = 'usuario__username'
	#end class
#end class

class SalidaListView(supra.SupraListView):
	model = models.Salida
	class Renderer:
		username = 'usuario__username'
	#end class
#end class

class RequisicionDeCompraListView(supra.SupraListView):
	model = models.RequisicionDeCompra
	list_display = ['codigo', 'usuario', 'fecha']
	class Renderer:
		def fecha(self, obj):
			return obj.fecha.strftime("%d-%m-%Y %I:%M%p")
		#end def
		usuario = 'usuario__username'
	#end class
#end class

class SolicitudDeProductoListView(supra.SupraListView):
	model = models.SolicitudDeProducto
	search_fields = ['producto_id']
	list_display = ['pk', 'nombre', 'presentacion', 'unidadades', 'cantidad']
	class Renderer:
		nombre = 'producto__nombre'
		presentacion = 'presentacion__nombre'
		unidadades = 'presentacion__unidades'
	#end class
#end class

from django.conf.urls import include, url
class RequisiscionDeCompraDetail(supra.SupraDetailView):
	model = models.RequisicionDeCompra
	class Renderer:
		productos = SolicitudDeProductoListView
	#end class

	def get_urls(self):
		return [
			url(r'^pdf/$', self.pdf,),
		]
	#end def

	@supra.view
	def pdf(self, request, context):
		return pdf.render(self.template_name, context)
	#end def
#end class

"""
"""

class SolicitudDeProductoDeleteView(supra.SupraDeleteView):
	model = models.SolicitudDeProducto
#end class

angularinv/templates/angularinv/dashboard.html
<h1>Dashboard</h1>
{{ hola }}
<input type="text" ng-model="hola">

angularinv/templates/angularinv/dirPagination.tpl.html
<ul class="pagination" ng-if="1 < pages.length || !autoHide">
    <li ng-if="boundaryLinks" ng-class="{ disabled : pagination.current == 1 }">
        <a href="" ng-click="setCurrent(1)">&laquo;</a>
    </li>
    <li ng-if="directionLinks" ng-class="{ disabled : pagination.current == 1 }">
        <a href="" ng-click="setCurrent(pagination.current - 1)">&lsaquo;</a>
    </li>
    <li ng-repeat="pageNumber in pages track by tracker(pageNumber, $index)" ng-class="{ active : pagination.current == pageNumber, disabled : pageNumber == '...' }">
        <a href="" ng-click="setCurrent(pageNumber)">[[pageNumber]]</a>
    </li>

    <li ng-if="directionLinks" ng-class="{ disabled : pagination.current == pagination.last }">
        <a href="" ng-click="setCurrent(pagination.current + 1)">&rsaquo;</a>
    </li>
    <li ng-if="boundaryLinks"  ng-class="{ disabled : pagination.current == pagination.last }">
        <a href="" ng-click="setCurrent(pagination.last)">&raquo;</a>
    </li>
</ul>   

angularinv/templates/angularinv/formRequisicion.html
 <div id="modal1" class="modal" >
    <div class="modal-content"> 	
		<form  method="post"  name="formR" ng-submit="formR.$valid && enviarForm()" novalidate>
		{% csrf_token %}
			<div class="row"> 
					<div class="input-field col s12">
						<input id="id_codigo" maxlength="45" name="codigo" type="text" required ng-model="data.codigo"/>
						<label for="id_codigo">Codigo:</label> 
					</div>
					<input id="id_solicituddeproducto_set-TOTAL_FORMS" name="solicituddeproducto_set-TOTAL_FORMS" type="hidden" value="[[total]]" ng-model="data.total"/>
					<input id="id_solicituddeproducto_set-INITIAL_FORMS" name="solicituddeproducto_set-INITIAL_FORMS" type="hidden" value="0" ng-model="data.initial"/>
					<input id="id_solicituddeproducto_set-MIN_NUM_FORMS" name="solicituddeproducto_set-MIN_NUM_FORMS" type="hidden" value="0" ng-model="data.min"/>
					<input id="id_solicituddeproducto_set-MAX_NUM_FORMS" name="solicituddeproducto_set-MAX_NUM_FORMS" type="hidden" value="1000" ng-model="data.max"/>
					<div ng-repeat="n in range(0, total)" >
						<div ng-hide="data.check[n]" ng-init="data.check[n]=false" ng-model="data.check[n]" class="row">
							<div  class="input-field col s3">
								<select  id="id_solicituddeproducto_set-[[n]]-producto" name="solicituddeproducto_set-[[n]]-producto" ng-model="data.producto[n]" ng-change="presentaciones(data.producto[n].presentaciones, n)" ng-options="pro as pro.nombre for pro in productos track by pro.id"> 
									<option value="" disabled selected="selected">---------</option>
								</select>
								<label for="id_solicituddeproducto_set-[[n]]-producto">Producto:</label> 
							</div>
							<div class="input-field col s3" >
								<select id="id_solicituddeproducto_set-[[n]]-presentacion" name="solicituddeproducto_set-[[n]]-presentacion" ng-disabled="activar[n]" ng-init="activar[n]=true" ng-model="data.presentacion[n]">
									<option value="" disabled selected="selected">---------</option>
									<option ng-repeat="pre in presentacionP" value="[[ pre.id ]]">[[ pre.nombre ]] [[ pre.unidades ]]</option>
								</select>
								<label for="id_solicituddeproducto_set-[[n]]-presentacion" >Presentacion:</label> 
							</div>
							<div class="input-field col s3">
								<input id="id_solicituddeproducto_set-[[n]]-cantidad" min="0" name="solicituddeproducto_set-[[n]]-cantidad" type="number"  ng-model="data.cantidad[n]"/>
								<label for="id_solicituddeproducto_set-[[n]]-cantidad">Cantidad:</label> 
							</div>
							<div class="input-field col s3">
								<input id="id_solicituddeproducto_set-[[n]]-DELETE" name="solicituddeproducto_set-[[n]]-DELETE" type="checkbox"  ng-change="selectDelete(n, data.deletE[n])" ng-model="data.deletE[n]"/>
								<label for="id_solicituddeproducto_set-[[n]]-DELETE">Eliminar</label> 
								<input id="id_solicituddeproducto_set-[[n]]-requisiciondecompra" name="solicituddeproducto_set-[[n]]-requisiciondecompra" type="hidden" />
								<input id="id_solicituddeproducto_set-[[n]]-id" name="solicituddeproducto_set-[[n]]-id" type="hidden" />
							</div>	
						</div>
					</div>
					<div class="row">
						<div class="col s6">
							<a href="" class="btn col s12" ng-click="addStact()">
							<i class="material-icons right">add</i>Agregar otro</a>
						</div>
						<div class="col s6">
							<a href="" class="btn col s12" ng-click="hideSelect()">
							<i class="material-icons right">delete</i>Eliminar selccionados</a>
						</div>
					</div>
					<div class="row">
						<div class="col s12">
							<button class="btn waves-effect waves-light col s12" type="submit" name="action">Enviar
						    	<i class="material-icons right">send</i>
							</button>	
						</div>	
					</div>
			</div> 
		</form>	
    </div>
  </div>

angularinv/templates/angularinv/inventario.html
<h1>Inventario</h1>

angularinv/templates/angularinv/recetas.html
<h1>Recetas</h1>

angularinv/templates/angularinv/requisicion.html
<div>
	<div id="filtro" class="row">
		<div class="input-field col ">
			<input type="date" name="fecha" class="datepicker" ng-model="searchdate" >
			<label for="fecha">Fecha Requisición</label>
		</div>
		<div class="input-field col">
			<input type="text" name="usuario" ng-model="search">
			<label for="ususario">Usuario</label>
		</div>
	</div>
	 <table class="highlight bordered">
        <thead>
          <tr>
              <th data-field="fecha" ng-click="sort('fecha')">Fecha de Requisición<span ng-show="sortKey=='fecha'"> <i class="tiny material-icons">grade</i></span></th>
              <th data-field="usuario" ng-click="sort('usuario_id')">Usuario<span ng-show="sortKey=='usuario_id'"> <i class="tiny material-icons">grade</i></span></th>
              <th data-field="codigo" ng-click="sort('codigo')">Codigo<span ng-show="sortKey=='codigo'"> <i class="tiny material-icons">grade</i></span></th>
              <th data-field="id" >Previsualizar</th>
              <th data-field>Imprimir</th>
          </tr>
        </thead>

        <tbody>
         <tr dir-paginate="reque in requesiciones |itemsPerPage:5|orderBy:sortKey:reverse|filter:search|filter:searchdate" >
         	<td>[[ reque.fecha | date:'yyyy/MM/dd HH:mm:ss' ]]</td>
         	<td>[[ reque.usuario_id ]]</td>
          <th>[[ reque.codigo ]]</th>
         	<td><a href="" ng-click="singleModal([[ reque.id ]])"><i class="material-icons">visibility</i></a></td>
         	<td><a href="/inventario/requisiciondecompra/detail/[[ reque.id ]]/pdf/"  target="_blank"><i class="material-icons">print</i></a></td>
         </tr>
        </tbody>
      </table>
        <dir-pagination-controls
          max-size="5"
          direction-links="true"
          boundary-links="true" 
          template-url="/angularinv/dirPagination.tpl.html">  
        </dir-pagination-controls>
      <add-form></add-form>
      <single-requisicion></single-requisicion>
	<div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
    	<a class="btn-floating btn-large waves-effect waves-light red modal-trigger" id="addRequisicion" ng-click="openModal()"><i class="material-icons">add</i></a>
    </div>
</div>

angularinv/templates/angularinv/singleRequisicion.html
 <div id="modal2" class="modal" >
    <div class="modal-content"> 	
		<div class="row">
			 <div class="col s12">
			 	<div class="card cardPropia center">
			 		<div class="card-content white-text">
			 		<span class="card-title">Requisición de Producto</span>
			 		<ul>
			 			<li><b>Fecha: </b>[[ singler.fecha |  date:'yyyy-MM-dd'  ]]</li>
			 			<li><b>Codigo: </b>[[ singler.codigo ]]</li>
			 			<li><b>Usuario: </b><span ng-if="singler.usuario=='None'">Sin asignar</span><span ng-if="singler.usuario!='None'">[[ singler.usuario ]]</span></li>
			 		</ul>
					</div>
			 	</div>
			 </div>
			 <div class="col s6" ng-repeat="producto in singler.productos.object_list">
		      <div class="card">
		        <div class="card-content">
		          <ul>
		          	<li><b>Producto: </b> [[ producto.nombre ]]</li>
		          	<li><b>Presentacion: </b>[[ producto.presentacion ]] [[ producto.unidadades ]]</li>
		          	<li><b>Cantidad:</b> [[ producto.cantidad ]]</li>
		          </ul>
		        </div>
		        <div class="card-action" ng-show="editar">
		          <a ng-click="eliminarP(producto)">Eliminar</a>
		        </div>
		      </div>
		    </div>
		</div>
		<div class="switch center" ng-show="singler.productos.object_list.length > 0">
		<b>Editar:</b>
	    <label>
	      Off
	      <input type="checkbox" ng-model="editar">
	      <span class="lever"></span>
	      On
	    </label>
	  </div>
    </div>
  </div>

angularinv/templates/angularinv/ventas.html
<h1>Ventas</h1>